=== rschleitzer/dazzle/examples/class.dtd
<!-- DTD for Java class specification -->
<!ELEMENT class (field*, method*)>
<!ATTLIST class
    name CDATA #REQUIRED
    package CDATA #REQUIRED>

<!ELEMENT field EMPTY>
<!ATTLIST field
    name CDATA #REQUIRED
    type CDATA #REQUIRED>

<!ELEMENT method (body?)>
<!ATTLIST method
    name CDATA #REQUIRED
    returnType CDATA #REQUIRED>

<!ELEMENT body (#PCDATA)>

=== rschleitzer/dazzle/examples/codegen-valid.xml
<?xml version="1.0"?>
<!DOCTYPE class SYSTEM "class.dtd">
<class name="Employee" package="com.example.hr">
  <field name="employeeId" type="long"/>
  <field name="name" type="String"/>
  <field name="department" type="String"/>
  <field name="salary" type="double"/>
  <method name="getId" returnType="long">
    <body>return employeeId;</body>
  </method>
  <method name="getName" returnType="String">
    <body>return name;</body>
  </method>
  <method name="calculateBonus" returnType="double">
    <body>return salary * 0.1;</body>
  </method>
</class>

=== rschleitzer/dazzle/examples/showcase.xml
<?xml version="1.0"?>
<!DOCTYPE class SYSTEM "class.dtd">
<class name="Account" package="com.example.banking">
  <field name="accountNumber" type="String"/>
  <field name="balance" type="double"/>
  <field name="owner" type="String"/>
  <method name="getAccountNumber" returnType="String"/>
  <method name="getBalance" returnType="double"/>
  <method name="deposit" returnType="void"/>
  <method name="withdraw" returnType="boolean"/>
</class>
